Publish docker image from a tag
linagora/esn-frontend-mailto pull request #83
Opened 2021-06-18 14:17 UTC by oubchid

2021-06-18 14:18 UTC, tanandy approved these changes

2021-06-18 14:32 UTC, alagane requested changes

2021-06-18 14:32 UTC, alagane commented on Jenkinsfile
> +              dockerImage.push('main')
```suggestion
            dockerImage.push('main')
```

2021-06-18 14:43 UTC, alagane approved these changes

2021-06-21 05:48 UTC, rezk2ll approved these changes

2021-06-21 05:48 UTC, merged